#!/usr/bin/env sh

echo "   MARMOT_MSG_LEVEL: ${MARMOT_MSG_LEVEL}"
echo " MARMOT_MSG_CHANNEL: ${MARMOT_MSG_CHANNEL}"
echo "MARMOT_MSG_WHISTLER: ${MARMOT_MSG_WHISTLER}"
echo " MARMOT_MSG_CONTENT: ${MARMOT_MSG_CONTENT}"
